Traceback (most recent call last):
  File "/Users/plab/anaconda/envs/currpy/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/plab/anaconda/envs/currpy/lib/python3.7/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/plab/anaconda/envs/currpy/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/plab/anaconda/envs/currpy/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/plab/anaconda/envs/currpy/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/Users/plab/anaconda/envs/currpy/lib/python3.7/site-packages/nbclient/client.py", line 536, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/plab/anaconda/envs/currpy/lib/python3.7/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/plab/anaconda/envs/currpy/lib/python3.7/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
renumberedAtlasNifti=nib.Nifti1Image(relabeledAtlas, atlasImg.affine, atlasImg.header)  

atlas_widget = NiftiWidget(renumberedAtlasNifti)
atlas_widget.nifti_plotter(colormap='nipy_spectral')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-6-75ed38da84ed>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mrenumberedAtlasNifti[0m[0;34m=[0m[0mnib[0m[0;34m.[0m[0mNifti1Image[0m[0;34m([0m[0mrelabeledAtlas[0m[0;34m,[0m [0matlasImg[0m[0;34m.[0m[0maffine[0m[0;34m,[0m [0matlasImg[0m[0;34m.[0m[0mheader[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m [0matlas_widget[0m [0;34m=[0m [0mNiftiWidget[0m[0;34m([0m[0mrenumberedAtlasNifti[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0matlas_widget[0m[0;34m.[0m[0mnifti_plotter[0m[0;34m([0m[0mcolormap[0m[0;34m=[0m[0;34m'nipy_spectral'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'NiftiWidget' is not defined
NameError: name 'NiftiWidget' is not defined

